"""add last_seen to ip_addresses

Revision ID: d0cf9f02ac75
Revises: 045795083826
Create Date: 2026-05-02 02:59:05.777532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0cf9f02ac75'
down_revision: Union[str, Sequence[str], None] = '045795083826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_addresses', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ip_addresses', 'last_seen')
    # ### end Alembic commands ###
